	[%
		TOKENS = {
			PLUGIN_NAME = "Put aside"
			PRESENTATION = "Put aside a document for the same borrower"
                        PUTASIDE_CONF = "Koha: Putaside Plugin: configuration"
                        CONF_TITLE = "Configuration"
                        ENABLED_ITEMTYPES = "Item types you can put aside"
                        SAVE_BUTTON = "Save"
                        EBADBARCODE  = "Can't find item with barcode: "
                        ENOTONLOAN   = "Is not on loan"
                        ECANTRESERVE  = "can't reserve this item"
                        EBADITYPE   = "You can't put aside a document with item type: "
                        ENTER_BARCODE = "Enter item barcode:"
                        ITEM_PUT_ASIDE = "Item put aside for "
                        TITLE = "Title"
                        AUTHOR = "Author"
                        BARCODE = "Barcode"
                        HOME_LIBRARY = "Home Library"
                        CALLNUMBER = "Call Number"
                        ITYPE = "Item Type"
                        NOTES = "Notes"
		}
	%]
