	[%
		TOKENS = {
			PLUGIN_NAME = "Mise de côté"
			PRESENTATION = "Met de côté un document pour le même lecteur"
                        PUTASIDE_CONF = "Koha, Module de mise de côté : configuration"
                        CONF_TITLE = "Paramétrage"
                        ENABLED_ITEMTYPES = "Catégories de prêt pouvant être mises de côté"
                        SAVE_BUTTON = "Enregistrer"
                        EBADBARCODE  = "Pas de document avec le code barre : "
                        ENOTONLOAN   = "n'est pas en prêt"
                        ECANTRESERVE  = "ne peut réserver ce document"
                        EBADITYPE   = "On ne peut pas mettre de côté de la catégorie de prêt :"
                        ENTER_BARCODE = "Entrez le code barre du document :"
                        ITEM_PUT_ASIDE = "Document mis de côté pour "
                        TITLE = "Titre"
                        AUTHOR = "Auteur"
                        BARCODE = "Code barre"
                        HOME_LIBRARY = "Bibliothèque"
                        CALLNUMBER = "Cote"
                        ITYPE = "Catégorie de prêt"
                        NOTES = "Notes"
                        

		}
	%]
